[package]
name = "manzana-uno-emu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
clap-num = "1"
crossterm = "0.26"
crossbeam-channel = "0.5"
tracing ="0.1"
tracing-subscriber = "0.3"
yamos6502 = "0.1"
